// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPAngular.Models;

namespace SPAngular.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200927162023_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SPAngular.Models.Employee", b =>
                {
                    b.Property<int?>("Empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Empid");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
